# NUMPY (NUMERICAL PYTHON)

In [2]:
import numpy

In [3]:
print(numpy.__version__)

1.18.1


In [4]:
import numpy as np

In [5]:
print(np.__version__)

1.18.1


In [9]:
#Question1
#Answer1:
arr1=np.array(range(2,51,3))
arr1                                              #Thats how we can also print array in numpy 

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [16]:
#Question2
#Answer2
import numpy as np
l1=[]
l2=[]
for i in range(5):
    temp=int(input())
    l1.append(temp)
print("\n")
for i in range(5):
    temp=int(input())
    l2.append(temp)
arr1=np.array(l1)
arr2=np.array(l2)
print(np.concatenate((arr1,arr2)))
print(np.sort(np.concatenate((arr1,arr2))))





1
2
5
2
7


0
12
6
34
23
[ 1  2  5  2  7  0 12  6 34 23]
[ 0  1  2  2  5  6  7 12 23 34]


In [21]:
#Question3 HOW TO FIND DIMENSION OF NDARRAY AND ITS SIZE
#Answer:
import numpy as np                                   #importing numpy
arr1=np.arange(4)
print(arr1)
print("Dimension of array1: ",arr1.ndim)               #Checking dimension of arr1,syntax->arr_name.ndim
print("Size of array1:",arr1.shape)                    #Checking size of arr1,syntax->arr_name.shape
arr2=np.arange(12).reshape(3,4)                        #reshape func to giving order of matrix
print(arr2)
print("Dimension of array2:",arr2.ndim)
print("Size of array2:",arr2.shape)


[0 1 2 3]
Dimension of array1:  1
Size of array1: (4,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Dimension of array2: 2
Size of array2: (3, 4)


In [43]:
#Question4 How to convert 1D array to 2D array
#Answer4:
arr1=np.arange(12)
print(arr1)
print("shape of array1:",arr1.shape)
print("dimension of array1:",arr1.ndim)
print("\n")
arr2=arr1[:,np.newaxis]                          #adding newaxis(new dimension),syntax->np.newaxis,it adds new axis
print(arr2)
print("shape of array2:",arr2.shape)
print("dimension of array2:",arr2.ndim)
print("\n")
arr3=np.expand_dims(arr1,axis=0)                #adding newaxis at specified position,syntax->np.expand_dims
print(arr3)
print("shape of array3:",arr3.shape)
print("dimension of array3:",arr3.ndim)
print("\n")

[ 0  1  2  3  4  5  6  7  8  9 10 11]
shape of array1: (12,)
dimension of array1: 1


[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
shape of array2: (12, 1)
dimension of array2: 2


[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
shape of array3: (1, 12)
dimension of array3: 2




In [57]:
#Question5
#Answer5:
import numpy as np
arr1=np.identity(3)
print(arr1)
arr2=np.zeros((3,3))
print(arr2)
print("Vertically Stacked:","\n",np.vstack((arr1,arr2)))
print("Horizontally Stacked:","\n",np.hstack((arr1,arr2)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Vertically Stacked: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Horizontally Stacked: 
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [66]:
#Question6
#Answer6:
arr1=np.array([1,2,5,1,8,12,12,5,2,8,7,5,2,1,7])
print(arr1)
arr2=np.unique(arr1,return_counts=True)                   #this is how we get unique numbers and their frquencies in an array
print(arr2)

[ 1  2  5  1  8 12 12  5  2  8  7  5  2  1  7]
(array([ 1,  2,  5,  7,  8, 12]), array([3, 3, 3, 2, 2, 2], dtype=int64))
